Repository ContentWarnings/WebFrontend, pull requests merged in 2023-03, with the labels that each got.

#17 Fix GitHub Pages deployment bugs
  package-lock.json
  public/404.html
  public/CNAME
  public/index.html
  src/pages/Search.tsx
Labels: bug

#19 Fix import, mobile optimizations
  public/icon1024.png
  public/index.html
  public/manifest.json
  src/components/Account/PasswordReset.tsx
  src/components/Account/PasswordResetCommit.tsx
  src/components/Account/Register.tsx
  src/components/Account/SignIn.tsx
  src/components/Account/Verify.tsx
  src/components/Home/MovieButton.tsx
  src/helpers/Importer.ts
  src/helpers/Toast.ts
  src/index.tsx
  src/pages/Home.tsx
  src/pages/MovieEntry.tsx
Labels: bug, enhancement

#21 Nate/UI fixes
  src/App.tsx
  src/components/Home/GenreButton.tsx
  src/components/Home/GenresSection.tsx
  src/components/MovieEntry/AddContentWarning.tsx
  src/components/MovieEntry/ContentWarningButton.tsx
  src/components/Search/MovieCell.tsx
  src/components/layout/Header.tsx
  src/components/shared/CWCell.tsx
  src/pages/Home.tsx
  src/pages/MovieEntry.tsx
  tailwind.config.js
Labels: enhancement

#20 Settings page
  package-lock.json
  package.json
  src/App.tsx
  src/components/MovieEntry/AddContentWarning.tsx
  src/components/Settings/AddDevice.tsx
  src/components/Settings/CWInput.tsx
  src/components/Settings/ContentSubmission.tsx
  src/components/Settings/DangerZone.tsx
  src/components/Settings/DeleteAccountButton.tsx
  src/components/Settings/MyProfile.tsx
  src/components/Settings/MyProfileSubmissions.tsx
  src/components/Settings/NoProfile.tsx
  src/components/Settings/ResetAccountButton.tsx
  src/components/Settings/Tabs.tsx
  src/components/Settings/WarningButton.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/shared/TextBox.tsx
  src/pages/AccountSettings.tsx
  src/pages/NotFound.tsx
  src/pages/Settings.tsx
Labels: enhancement
